name: Tryout Repo 200 Lib Receive

on:
  repository_dispatch:
    types: [lib-update-event]

jobs:
  libUpdateEvent:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0

      - name: Extract Dependency Name
        id: lib
        uses: actions/github-script@v2.0.0
        with:
          result-encoding: string
          script: |
            console.log("data - data : ", JSON.stringify(context));
            let payload = context.github.event.client_payload;
            let revision = payload.tag_name.replace('v', '@');
            return payload.public_package + revision;

      - name: Update Dependency
        run: npm install ${{steps.lib.outputs.result}} --save --save-exact

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: Update dependency to ${{ steps.lib.outputs.result }}
          title: Update library -  ${{steps.lib.outputs.result}}
          body: |
            Auto generated pull request for upgrading to ${{steps.lib.outputs.result}}.
            For details vist: {{context.github.event.client_payload.html_url}}
