name: Tryout Repo 200 Lib Receive

on:
  repository_dispatch:
    types: [lib-update-event]

jobs:
  libUpdateEvent:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Extract Dependency Name
        id: lib
        uses: actions/github-script@v2.0.0
        with:
          result-encoding: string
          script: |
            let clientPayload = context.payload.client_payload;
            let publicPackageName = clientPayload.public_package;
            let revision = clientPayload.tag_name.replace('v', '');
            let packageName = publicPackageName + '@' + revision;
            return packageName;

      - name: Print new Package Name
        env:
          NEW_PKG: ${{steps.lib.outputs.result}}
        run: echo "$NEW_PKG"

      - name: Update Dependency
        run: npm install ${{steps.lib.outputs.result}} --save --save-exact

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: Update dependency to ${{ steps.lib.outputs.result }}
          title: Update library -  ${{steps.lib.outputs.result}}
          body: |
            Auto generated pull request for upgrading to ${{steps.lib.outputs.result}}.
            For details vist: {{context.github.event.client_payload.html_url}}
