name: Tryout Repo 200 Lib Update

on:
  registry_package:
    types: [published]

jobs:

  build:
    name: Debug Action Print
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Git checkout
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
